export const tasks = [
  {
    id: 1,
    title: "Task 1",
    description: "This is task 1",
    status: "pending",
    created_at: new Date(Date.now()),
    updated_at: new Date(Date.now()),
  },
  {
    id: 2,
    title: "Task 2",
    description: "This is task 2",
    status: "completed",
    created_at: new Date(Date.now()),
    updated_at: new Date(Date.now()),
  },
  {
    id: 3,
    title: "Task 3",
    description: "This is task 3",
    status: "in-progress",
    created_at: new Date(Date.now()),
    updated_at: new Date(Date.now()),
  },
  {
    id: 4,
    title: "Task 4",
    description: "This is task 4",
    status: "pending",
    created_at: new Date(Date.now()),
    updated_at: new Date(Date.now()),
  },
  {
    id: 5,
    title: "Task 5",
    description: "This is task 5",
    status: "completed",
    created_at: new Date(Date.now()),
    updated_at: new Date(Date.now()),
  },
  {
    id: 6,
    title: "Task 6",
    description: "This is task 6",
    status: "in-progress",
    created_at: new Date(Date.now()),
    updated_at: new Date(Date.now()),
  },
  {
    id: 7,
    title: "Task 7",
    description: "This is task 7",
    status: "pending",
    created_at: new Date(Date.now()),
    updated_at: new Date(Date.now()),
  },
  {
    id: 8,
    title: "Task 8",
    description: "This is task 8",
    status: "pending",
    created_at: new Date(Date.now()),
    updated_at: new Date(Date.now()),
  },
  {
    id: 9,
    title: "Task 9",
    description: "This is task 9",
    status: "completed",
    created_at: new Date(Date.now()),
    updated_at: new Date(Date.now()),
  },
  {
    id: 10,
    title: "Task 10",
    description: "This is task 10",
    status: "in-progress",
    created_at: new Date(Date.now()),
    updated_at: new Date(Date.now()),
  },
];
